name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  #Descarga el código
      - run: npm install           #Instala las dependencias
      - run: npm test              #Ejecuta pruebas
      - run: echo "✅Todo listo!!! Taran!!! ✅"  #Mensaje