name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository / Descargando el código (simulado)
        uses: actions/checkout@v4   #Descarga el código
      
      - name: Echo Step 1 / Instalando dependencias (simulado)
        run: echo "npm install"           #Instala las dependencias

      - name: Echo Step 2 / Ejecutando pruebas (simulado) 
        run: echo "npm test"              #Ejecuta pruebas

      - name: Echo Step 3 / Todo Listo
        run: echo "✅All done!!! Taran!!! ✅"  #Mensaje